on:
  push:
    branches:
      - master

jobs:
  # JOB to run change detection
  changes:
    runs-on: self-hosted
    permissions:
      pull-requests: read
    outputs:
      jobs: ${{ steps.filter.outputs.nomadjobs_files }}
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: 'json'
        filters: |
          nomadjobs: 
            - 'plex/*.job'
            - 'audioserver/*.job'
            - 'bitwarden/*.job'
            - 'coredns/*.job'
            - 'deconz/*.job'
            - 'docker-registry/*.job'
            - 'github-runner/*.job'
            - 'grafana/*.job'
            - 'home-assistant/*.job'
            - 'keepalived/*.job'
            - 'lidarr/*.job'
            - 'loki/*.job'
            - 'mqtt-pub/*.job'
            - 'ombi/*.job'
            - 'owntracks-recorder/*.job'
            - 'pihole/*.job'
            - 'plex/*.job'
            - 'prometheus/*.job'
            - 'radarr/*.job'
            - 'sabnzbd/*.job'
            - 'sickchill/*.job'
            - 'smtp/*.job'
            - 'sonarr/*.job'
            - 'tailscale/*.job'
            - 'telegraf/*.job'
            - 'traefik-ingress/*.job'
            - 'vector/*.job'
            - 'www/*.job'

  deploy:
    runs-on: self-hosted
    needs: changes
    continue-on-error: true
    strategy:
      matrix:
        job: ${{ fromJSON(needs.changes.outputs.jobs ) }}

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'

    - uses: lucasmelin/setup-nomad@v1

    - name: deploy
      shell: bash
      run: |
        nomad job run ${{ matrix.job }}
      env:
        NOMAD_ADDR: 'http://nomad.service.home:4646'
        NOMAD_VAR_region: 'home'
        NOMAD_VAR_tld: '.demonsafe.com'
        NOMAD_VAR_shared_dir: '/home/shared/'
        NOMAD_VAR_downloads_dir: '/home/sabnzbd/downloads'
        NOMAD_VAR_music_dir: '/home/media/Music'
        NOMAD_VAR_movies_dir: '/home/media/Movies'
        NOMAD_VAR_books_dir: '/home/media/Books'
        NOMAD_VAR_tv_dir: '/home/media/TV'
        NOMAD_VAR_media_dir: '/home/media'
        NOMAD_VAR_auth: '${{ secrets.NOMAD_VAR_AUTH }}'
        NOMAD_VAR_otr_pass: '${{ secrets.NOMAD_VAR_OTR_PASS }}'
        NOMAD_VAR_web_pass: '${{ secrets.NOMAD_VAR_WEB_PASS }}'
        NOMAD_VAR_hass_key: '${{ secrets.NOMAD_VAR_HASS_KEY }}'
        NOMAD_VAR_github_pat: ${{ secrets.NOMAD_VAR_GITHUB_PAT }}
        NOMAD_VAR_datacenters_all: '["dc1", "hetzner"]'
        NOMAD_VAR_datacenters_dc1: '["dc1"]'
        NOMAD_VAR_datacenters_public: '["hetzner"]'
